In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\HP\Downloads\customer_shopping_behavior.csv")

In [4]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [5]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [6]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [8]:
labels = ['Young adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels = labels)

In [10]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young adult
2   50  Middle-aged
3   21  Young adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young adult
8   26  Young adult
9   57  Middle-aged

In [12]:
frequency_mapping = { 'Fortnightly':14,
                      'Bi-Weekly':14,
                      'Every 3 Months':90,
                      'Quarterly':90,
                      'Annually':365,
                      'Weekly':7,
                      'Monthly':30}
df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [15]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [17]:
df= df.drop('promo_code_used', axis =1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "mysql+pymysql://root:Naresh@11@localhost:3306/customer_behavior"
)

In [4]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "mysql+pymysql",
    username="root",
    password="Naresh@11",
    host="localhost",
    port=3306,
    database="customer_behavior"
)

engine = create_engine(connection_url)

In [5]:
with engine.connect() as connection:
    print("MySQL connection successful!")

MySQL connection successful!

In [6]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('customer_behavior',)

In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\Downloads\customer_shopping_behavior.csv")

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
table_name = 'customer'
df.to_sql(
    name="customer",
    con=engine,
    if_exists="replace",
    index=False
)

3900

In [10]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [11]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [12]:
df['Review Rating']= df.groupby('Category')["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [13]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [14]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [16]:
labels = ['Young adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels = labels)

In [17]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young adult
2   50  Middle-aged
3   21  Young adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young adult
8   26  Young adult
9   57  Middle-aged

In [18]:
frequency_mapping = { 'Fortnightly':14,
                      'Bi-Weekly':14,
                      'Every 3 Months':90,
                      'Quarterly':90,
                      'Annually':365,
                      'Weekly':7,
                      'Monthly':30}
df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [20]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [21]:
df= df.drop('promo_code_used', axis =1)

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [23]:
df.to_sql(
    name="customer",
    con=engine,
    if_exists="replace",
    index=False
)

3900

In [24]:
import os
print(os.path.abspath("customer_shopping_analysis.ipynb"))

C:\Users\HP\customer_shopping_analysis.ipynb